# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3.10

repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [ --line-length=120, --target-version=py39 ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3
        args: [ --max-line-length=120, --extend-ignore=E203 ]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        args: [ --py39-plus ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [ click, numpy, torch, wandb ]
        args: [ --config-file=mypy.ini ]

exclude: '^(.idea/|wandb/)'
