name: mocca
dependencies:
  - conda-forge::cudatoolkit=11.6
  - pytorch::pytorch=1.12.*=*cuda*
  - pytorch::torchvision=0.13.*=*cu*
  - conda-forge::matplotlib=3.6.*
  - conda-forge::mypy=0.991
  - conda-forge::numpy=1.23.*
  - conda-forge::pandas=1.5.*
  - Pillow=9.2.*
  - conda-forge::pre-commit=2.20.*
  - conda-forge::prettytable=3.4.*
  - conda-forge::pudb=2022.*
  - python=3.10.*
  - conda-forge::scikit-build=0.15.*
  - conda-forge::scikit-image=0.19.*
  - conda-forge::scikit-learn=1.1.*
  - conda-forge::tensorboard=2.10.*
  - conda-forge::tensorboardX=2.5.*
  - tqdm=4.64.*
  - pip
  - pip:
      - opencv-python<4.6
