name: mocca_nano
dependencies:
  - conda-forge::cudatoolkit=11.5.*
  - pytorch::pytorch=1.11.*=*cuda*
  - pytorch::torchvision=0.12.*=*cu*
  - conda-forge::matplotlib=3.6.*
  - conda-forge::mypy=0.991
  - conda-forge::numpy=1.24.*
  - conda-forge::pandas=1.5.*
  - conda-forge::Pillow=9.4.*
  - conda-forge::pre-commit=2.21.*
  - conda-forge::prettytable=3.6.*
  - conda-forge::pudb=2022.1.*
  - python=3.10.*
  - conda-forge::scikit-build=0.16.*
  - conda-forge::scikit-image=0.19.*
  - conda-forge::scikit-learn=1.2.*
  - conda-forge::tensorboard=2.11.*
  - conda-forge::tensorboardX=2.5.*
  - tqdm=4.64.*
  - pip
  - pip:
      - opencv-python<4.6
